/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulesModuleIdRouteImport } from './routes/modules.$moduleId'
import { Route as AdminModulesModuleIdRouteImport } from './routes/admin.modules.$moduleId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleIdRoute = ModulesModuleIdRouteImport.update({
  id: '/$moduleId',
  path: '/$moduleId',
  getParentRoute: () => ModulesRoute,
} as any)
const AdminModulesModuleIdRoute = AdminModulesModuleIdRouteImport.update({
  id: '/modules/$moduleId',
  path: '/modules/$moduleId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/modules': typeof ModulesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/modules/$moduleId': typeof ModulesModuleIdRoute
  '/admin/modules/$moduleId': typeof AdminModulesModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/modules': typeof ModulesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/modules/$moduleId': typeof ModulesModuleIdRoute
  '/admin/modules/$moduleId': typeof AdminModulesModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/modules': typeof ModulesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/modules/$moduleId': typeof ModulesModuleIdRoute
  '/admin/modules/$moduleId': typeof AdminModulesModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/leaderboard'
    | '/modules'
    | '/profile'
    | '/settings'
    | '/modules/$moduleId'
    | '/admin/modules/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/leaderboard'
    | '/modules'
    | '/profile'
    | '/settings'
    | '/modules/$moduleId'
    | '/admin/modules/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/leaderboard'
    | '/modules'
    | '/profile'
    | '/settings'
    | '/modules/$moduleId'
    | '/admin/modules/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ModulesRoute: typeof ModulesRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$moduleId': {
      id: '/modules/$moduleId'
      path: '/$moduleId'
      fullPath: '/modules/$moduleId'
      preLoaderRoute: typeof ModulesModuleIdRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/admin/modules/$moduleId': {
      id: '/admin/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/admin/modules/$moduleId'
      preLoaderRoute: typeof AdminModulesModuleIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminModulesModuleIdRoute: typeof AdminModulesModuleIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminModulesModuleIdRoute: AdminModulesModuleIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ModulesRouteChildren {
  ModulesModuleIdRoute: typeof ModulesModuleIdRoute
}

const ModulesRouteChildren: ModulesRouteChildren = {
  ModulesModuleIdRoute: ModulesModuleIdRoute,
}

const ModulesRouteWithChildren =
  ModulesRoute._addFileChildren(ModulesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  LeaderboardRoute: LeaderboardRoute,
  ModulesRoute: ModulesRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
